- name: Install nginx
  tags: install, nginx
  apt:
    name: nginx
    state: latest

- name: Start nginx
  tags: install, nginx
  service:
    name: nginx
    state: started


- name: Restart nginx
  tags: subdomain
  service:
    name: nginx
    state: restarted
