
- name: Install the gpg key for Grafana + Grafana repos
  deb822_repository:
    name: Grafana
    types: deb
    trusted: true
    uris: https://apt.grafana.com
    components: stable
    suites: main
    signed_by: https://apt.grafana.com/gpg.key 

# - name: Install the gpg key for Grafana + Grafana repos
#   block:
#     - name: Grafana repo key
#       get_url:
#         url: https://apt.grafana.com/gpg.key
#         dest: /etc/apt/keyrings/grafana.gpg
#     - name: Add Grafana stable repos
#       apt_repository:
#         repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
#         state: present
#         update_cache: yes
- name: Install the Grafana packages
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Start the Grafana server
  systemd_service:
    daemon_reload: yes
    state: started
    name: grafana-server
    enabled: true
