---
- hosts: host
  remote_user: root

  vars_prompt:
    - name: ctid
      prompt: 'Specify container ID or leave blank for all'
      private: no

  tasks:
      - name: Backup all containers.
        command:
            cmd: vzdump --all --maxfiles 5 --compress zstd --mode stop
        when: ctid == ""

      - name: Backup specified container.
        command:
            cmd: vzdump {{ ctid }} --maxfiles 5 --compress zstd --mode stop
        when: ctid != ""
