---
# creates and starts containers from host vars
- name: 'deploy containers'

  hosts: 'host'
  gather_facts: false

  handlers:
  - name: 'sleep'
    pause:
      seconds: 10

  tasks:
  - name: 'include vars'
    include_vars: '../group_vars/host/vars.yml'

  - name: 'create containers'
    proxmox:
      vmid: '{{ item.value.vmid | default([])}}'
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      hostname: '{{ item.key }}'
      node: '{{ item.value.node }}'
      password: '{{ item.value.password }}'
      cores: '{{ item.value.cores | default(defaults.cores) }}'
      cpus: '{{ item.value.cpu | default(defaults.cpu) }}'
      memory: '{{ item.value.memory | default(defaults.memory.ct) }}'
      swap: '{{ item.value.swap | default([]) }}'
      disk: '{{ item.value.disk | default(defaults.disk) }}'
      #mounts: '{{ item.value.mounts | default([]) }}'
      netif: '{{ item.value.netif | default([]) }}'
      storage: '{{ item.value.storage | default(defaults.storage.ct) }}'
      onboot: '{{ item.value.onboot | default(defaults.onboot) }}'
      nameserver: '{{ item.value.nameserver | default(defaults.nameserver) }}'
      ostemplate: '{{ item.value.ostemplate | default(defaults.ostemplate) }}'
      state: 'present'
    with_dict: "{{ cts }}"
    loop_control:
      pause: 5
    notify:
      - 'sleep'
    register: 'created_cts_pve'
    when: 'not item.value.cloudinit | default(false) | bool'

  - meta: 'flush_handlers'
    when: 'created_cts_pve.changed'

  - name: 'start ct deployment'
    proxmox:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      node: "{{ item.item.value.node }}"
      hostname: "{{ item.item.key }}"
      state: 'started'
    with_items: "{{ created_cts_pve.results }}"
    notify:
      - 'sleep'
    when: 'item.changed'

  - meta: 'flush_handlers'
    when: 'created_vms_pve.changed'
