---
- hosts: nodejs
  tasks:
  - name: Add system user
    user:
      name: ctgs
      groups: sudo
      append: yes
      shell: /bin/bash
      create_home: yes

  - name: Install nginx
    tags: install, nginx
    apt:
      name: nginx
      state: latest

  - name: Start nginx
    tags: install, nginx
    service:
      name: nginx
      state: started

  roles:
    - ddns
    - nodejs
    - closingtags
    # - certbot
