---
- hosts: nodejs
  tasks:
  - name: Add system user
    user:
      name: ctgs
      groups: sudo
      append: yes
      shell: /bin/bash
      create_home: yes

  roles:
    - ddns
    - nginx
    - nodejs
    - closingtags
    # - certbot
