---
- name: prep host for automation
  hosts: host
  vars:
      packages:
          - python3-pip
          - build-essential

  tasks:
   - name: disable enterprise repos
     apt_repository:
       repo: 'deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
       state: absent
   - name: switch to community repos
     apt_repository:
       repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
       state: present
   - name: Update all packages to the latest version
     apt:
       upgrade: dist
   - name: Install pip packages
     apt:
       name: "{{ packages }}"
       state: latest
   - name: pip update pip
     pip:
       name: pip
       state: latest
   - name: Install virtualenv
     pip:
       name: virtualenv
       state: latest
   - name: Install proxmoxer
     pip:
       name: proxmoxer
       state: latest
