---
- name: 'stop and remove container'
  hosts: 'host'

  handlers:
  - name: 'sleep'
    pause:
      seconds: 5

  tasks:
  - name: 'stop container 104'
    proxmox:
      vmid: '104'
      api_user: 'root@pam'
      api_password: '{{ vault_api_password }}'
      api_host: 'localhost'
      state: stopped
    notify:
      - 'sleep'

  - name: 'remove container 104'
    proxmox:
      vmid: '104'
      api_user: 'root@pam'
      api_password: '{{ vault_api_password }}'
      api_host: 'localhost'
      state: absent
