---
- name: stop and remove container
  hosts: host

  handlers:
  - name: 'sleep'
    pause:
      seconds: 5

  tasks:
  - name: stop container 102
    proxmox:
      vmid: '102'
      api_user: 'root@pam'
      api_password: '{{ vault_api_password }}'
      api_host: 'localhost'
      state: stopped
    notify:
      - 'sleep'

  - name: remove container 102
    proxmox:
      vmid: '102'
      api_user: 'root@pam'
      api_password: '{{ vault_api_password }}'
      api_host: 'localhost'
      state: absent
