- name: create containers
  tags: proxmox, create, deploy
  proxmox:
    proxmox_default_behavior: 'no_defaults'
    vmid: '{{ item.value.vmid | default([])}}'
    api_user: "{{ api_user }}"
    # api_password: "{{ api_password }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}" 
    api_host: "{{ api_host }}"
    hostname: '{{ item.key }}'
    node: '{{ item.value.node | default(defaults.node) }}'
    password: '{{ item.value.password }}'
    pubkey: '{{ item.value.pubkey | default(defaults.pubkey) }}'
    cores: '{{ item.value.cores | default(defaults.cores) }}'
    cpus: '{{ item.value.cpu | default(defaults.cpu) }}'
    memory: '{{ item.value.memory | default(defaults.memory.ct) }}'
    swap: '{{ item.value.swap | default([]) }}'
    # disk: '{{ item.value.disk | default(defaults.disk) }}'
    #mounts: '{{ item.value.mounts | default([]) }}'
    netif: '{{ item.value.netif | default([]) }}'
    storage: '{{ item.value.storage | default(defaults.storage.ct) }}'
    onboot: '{{ item.value.onboot | default(defaults.onboot) }}'
    nameserver: '{{ item.value.nameserver | default(defaults.nameserver) }}'
    ostemplate: '{{ item.value.ostemplate | default(defaults.ostemplate) }}'
    state: 'present'
  with_dict: "{{ cts }}"
  loop_control:
    pause: 5
  notify:
    - sleep
  register: 'created_cts_pve'
  when: 'not item.value.cloudinit | default(false) | bool'


- meta: flush_handlers

- name: start ct deployment
  tags: proxmox, create, deploy
  proxmox:
    api_user: "{{ api_user }}"
    # api_password: "{{ api_password }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}" 
    api_host: "{{ api_host }}"
    node: '{{ item.value.node | default(defaults.node) }}'
    hostname: "{{ item.item.key }}"
    state: started
  with_items: "{{ created_cts_pve.results }}"
  notify:
    - sleep
  when: item.changed
