---
# container variables
100_password: '{{ vault_100 }}'
101_password: '{{ vault_101 }}'
102_password: '{{ vault_102 }}'
103_password: '{{ vault_103 }}'
104_password: '{{ vault_104 }}'
105_password: '{{ vault_105 }}'

cts:
  plex:
    vmid: '100'
    type: 'ubuntu'
    memory: '1024'
    swap: '1024'
    cores: '1'
    storage: 'local-zfs'
    mounts: '{"mp0":"/mnt/shared,mp=/media/mount"}'
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.67/24,bridge=vmbr0,firewall=1"}'
    password: "{{ vault_100 }}"
  closingtags:
    vmid: '101'
    type: 'ubuntu'
    memory: '1024'
    swap: '512'
    cores: '1'
    storage: 'local-zfs'
    disk: '10'
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.68/24,bridge=vmbr0,firewall=1"}'
    ostemplate: 'local:vztmpl/Ubuntu16.04-nginx-mariadb-php7-certbot-git.tar.gz'
    password: "{{ vault_101 }}"
  zoneminder:
    vmid: '102'
    type: 'ubuntu'
    memory: '512'
    swap: '512'
    cores: '1'
    storage: 'local-zfs'
    disk: '80'
    onboot: false
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.69/24,bridge=vmbr0,firewall=1"}'
    password: "{{ vault_102 }}"
  pihole:
    vmid: '103'
    type: 'ubuntu'
    memory: '512'
    swap: '512'
    cores: '1'
    storage: 'local-zfs'
    disk: '80'
    onboot: false
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.65/24,bridge=vmbr0,firewall=1"}'
    password: "{{ vault_103 }}"
  vpn:
    vmid: '104'
    type: 'ubuntu'
    memory: '1024'
    swap: '1024'
    cores: '1'
    disk: '16'
    storage: 'local-zfs'
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.70/24,bridge=vmbr0,firewall=1"}'
    ostemplate: 'local:vztmpl/ubuntu-16.04-standard_16.04-1_amd64.tar.gz'
    #mounts: '{"mp0":"/mnt/shared,mp=/media/mount"}'
    password: "{{ vault_104 }}"
  cloud:
    vmid: '105'
    type: 'ubuntu'
    memory: '512'
    swap: '512'
    cores: '1'
    disk: '20'
    storage: 'local-zfs'
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.71/24,bridge=vmbr0,firewall=1"}'
    ostemplate: 'local:vztmpl/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz'
    #mounts: '{"mp0":"/mnt/shared,mp=/media/mount"}'
    password: "{{ vault_105 }}"
  test:
    vmid: '106'
    type: 'ubuntu'
    memory: '512'
    swap: '512'
    cores: '1'
    disk: '20'
    storage: 'local-zfs'
    netif: '{"net0":"name=eth0,gw=192.168.1.1,ip=192.168.1.72/24,bridge=vmbr0,firewall=1"}'
    ostemplate: 'local:vztmpl/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz'
    #mounts: '{"mp0":"/mnt/shared,mp=/media/mount"}'
    password: "sample"
#vms:
#  test_vm:
#    name: 'test_vm'
#    vmid: '104'
#    cores: '1'
#    memory: '1024'
#    net: 
