---
# proxmox and proxmox_kvm options
api_user: 'root@pam'
api_password: '{{ vault_api_password }}'
api_host: 'localhost'
defaults:
  cores: '1'
  cpu: '1'
  memory:
    ct: '1024'
  onboot: true
  node: 'pve'
  pubkey: '%'
  disk: '8'
  nameserver: '192.168.1.65'
  storage:
    ct: 'local'
  ostemplate: 'local:vztmpl/ubuntu-20.10-standard_20.10-1_amd64.tar.gz'

