
- name: Add ddns bash script
  tags: ddns, bash
  copy:
    src: ddns.sh # https://gist.github.com/Dilden/cbe4787b5e776eb13989df1ba8b54612
    dest: /root/ddns.sh
    owner: root
    group: root
    mode: 0744

- name: Setup cronjob to update DNS
  cron:
    name: ddns cron
    user: www-data
    job: '/root/ddns.sh'
    minute: '*/20'
    state: present
