- name: Update apt cache, upgrade packages, remove useless packages from cache, remove dependencies that are no longer required
  tags: upgrade
  apt:
    update_cache: yes
    # upgrade: dist
    # autoclean: yes
    # autoremove: yes

- name: Install required packages
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
      - apt-transport-https
      - wget
      - python3-debian
      - python3-apt
      - gpg
    state: present
