- name: Update apt cache, upgrade packages, remove useless packages from cache, remove dependencies that are no longer required
  tags: upgrade
  apt:
    update_cache: yes
    upgrade: dist
    autoclean: yes
    autoremove: yes
  register:
    changes
- debug:
    var: changes.stdout_lines
