- name: Build helth app locally
  tags: helth, build, deploy
  shell: npm run build
  args:
    chdir: ~/Dev/projects/helth/
  delegate_to: 127.0.0.1

- name: Copy build to server
  tags: helth, build, deploy
  copy:
    src: ~/Dev/projects/helth/build/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy package-lock.json to server
  tags: helth, build, deploy
  copy:
    src: ~/Dev/projects/helth/package-lock.json
    dest: /var/www/html/package-lock.json
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy package.json to server
  tags: helth, build, deploy
  copy:
    src: ~/Dev/projects/helth/package.json
    dest: /var/www/html/package.json
    owner: www-data
    group: www-data
    mode: 0644

- name: Create service file
  tags: helth, build, deploy
  template:
    src: files/service
    dest: /etc/systemd/system/nodejs.service
  register: service_conf

- name: Reload systemd daemon
  tags: helth, build, deploy, systemd
  systemd:
    daemon_reload: yes
  when: service_conf.changed

- name: Install dependencies from lockfile
  tags: helth, build, deploy
  shell: npm ci --ignore-scripts
  args:
    chdir: /var/www/html/

- name: Restart NodeJS service
  tags: helth, build, deploy
  service:
    name: nodejs
    state: restarted
    enabled: yes
